In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# The following function calculates the Hamming score that calculates the multilabel accuracy. 
## In most sklearn models, it will be the same as the accuracy calculated with the "model.score()" function!

In [115]:
def hamming_score(y_true, y_pred, normalize=True, sample_weight=None):
    '''
    Compute the Hamming score (a.k.a. label-based accuracy) for the multi-label case
    https://stackoverflow.com/q/32239577/395857
    '''
    acc_list = []
    for i in range(y_true.shape[0]):
        set_true = set( np.where(y_true[i])[0] )
        set_pred = set( np.where(y_pred[i])[0] )
        #print('\nset_true: {0}'.format(set_true))
        #print('set_pred: {0}'.format(set_pred))
        tmp_a = None
        if len(set_true) == 0 and len(set_pred) == 0:
            tmp_a = 1
        else:
            tmp_a = len(set_true.intersection(set_pred))/\
                    float( len(set_true.union(set_pred)) )
        #print('tmp_a: {0}'.format(tmp_a))
        acc_list.append(tmp_a)
    return np.mean(acc_list)



In [2]:
X_dev = pd.read_csv("X_dev.csv")

In [3]:
y_dev = pd.read_csv("y_dev.csv")

In [4]:
#X_test = pd.read_csv(r"F:\project\X_test.csv")

In [5]:
#y_test = pd.read_csv(r"F:\project\y_test.csv")

In [6]:
#X_train = pd.read_csv(r"F:\project\X_train.csv")

In [7]:
#y_train = pd.read_csv(r"F:\project\y_train.csv")

In [4]:
X_dev.dtypes

Unnamed: 0                     int64
reordered                      int64
product_popularity_cnt       float64
department_popularity_cnt    float64
IsOrganic                       bool
order_HourGroup               object
days_previous_Group            int64
Percentage_amount_product    float64
dtype: object

In [5]:
y_dev.head()

Unnamed: 0  4605  4920  5876  8277  13176  16797  19057  21137  21616  \
0     1612274     0     0     0     0      0      0      0      0      0   
1      404649     0     0     0     1      0      0      0      0      0   
2     2553704     0     0     0     0      0      0      0      0      0   
3     2288426     0     0     0     0      0      0      0      0      0   
4     3099956     0     0     0     0      0      0      0      1      0   

   ...    40706  42265  44632  45007  45066  47209  47626  47766  49235  49683  
0  ...        0      0      0      0      0      0      0      0      0      0  
1  ...        0      0      0      0      0      0      0      0      0      0  
2  ...        0      0      0      0      0      0      0      0      0      0  
3  ...        0      0      0      0      0      0      0      0      0      0  
4  ...        0      0      0      0      0      0      0      0      0      0  

[5 rows x 31 columns]

In [6]:
y_dev.dtypes

Unnamed: 0    int64
4605          int64
4920          int64
5876          int64
8277          int64
13176         int64
16797         int64
19057         int64
21137         int64
21616         int64
21903         int64
22935         int64
24852         int64
24964         int64
26209         int64
27845         int64
27966         int64
28204         int64
30391         int64
37646         int64
39275         int64
40706         int64
42265         int64
44632         int64
45007         int64
45066         int64
47209         int64
47626         int64
47766         int64
49235         int64
49683         int64
dtype: object

In [7]:
y_dev.describe()

Unnamed: 0           4605           4920           5876  \
count  4.025120e+05  402512.000000  402512.000000  402512.000000   
mean   2.014323e+06       0.017540       0.020558       0.021252   
std    1.162091e+06       0.131272       0.141901       0.144222   
min    6.500000e+01       0.000000       0.000000       0.000000   
25%    1.008802e+06       0.000000       0.000000       0.000000   
50%    2.012601e+06       0.000000       0.000000       0.000000   
75%    3.021697e+06       0.000000       0.000000       0.000000   
max    4.025104e+06       1.000000       1.000000       1.000000   

                8277          13176          16797          19057  \
count  402512.000000  402512.000000  402512.000000  402512.000000   
mean        0.020548       0.092854       0.035311       0.018375   
std         0.141867       0.290229       0.184564       0.134302   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

               21137          21616      ...                40706  \
count  402512.000000  402512.000000      ...        402512.000000   
mean        0.064497       0.017562      ...             0.020491   
std         0.245637       0.131354      ...             0.141674   
min         0.000000       0.000000      ...             0.000000   
25%         0.000000       0.000000      ...             0.000000   
50%         0.000000       0.000000      ...             0.000000   
75%         0.000000       0.000000      ...             0.000000   
max         1.000000       1.000000      ...             1.000000   

               42265          44632          45007          45066  \
count  402512.000000  402512.000000  402512.000000  402512.000000   
mean        0.019155       0.018372       0.026091       0.019642   
std         0.137069       0.134293       0.159407       0.138766   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

               47209          47626          47766          49235  \
count  402512.000000  402512.000000  402512.000000  402512.000000   
mean        0.051839       0.038133       0.041671       0.018921   
std         0.221703       0.191518       0.199836       0.136247   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

               49683  
count  402512.000000  
mean        0.023410  
std         0.151203  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [16]:
rowSums = y_dev.sum(axis=0)
rowSums

Unnamed: 0    810789345757
4605                  7060
4920                  8275
5876                  8554
8277                  8271
13176                37375
16797                14213
19057                 7396
21137                25961
21616                 7069
21903                23754
22935                11316
24852                46049
24964                10615
26209                13719
27845                13604
27966                13616
28204                 8756
30391                 8048
37646                 7210
39275                 9863
40706                 8248
42265                 7710
44632                 7395
45007                10502
45066                 7906
47209                20866
47626                15349
47766                16773
49235                 7616
49683                 9423
dtype: int64

In [6]:
X_dev['IsOrganic'] = X_dev['IsOrganic'].astype('int')

In [7]:
X_dev['order_HourGroup'] =X_dev['order_HourGroup'].astype('category')


In [8]:
def one_hot_encoding(data,var,drop=True):
    #res = []
    #nm = data[var].name
    nn = data[var].unique()
    for i in nn:
        s = '%s_%s' % (var,i)
        data[s] = 0
        data.loc[data[var]==i,s] = 1
        #res.append(newx)
    if(drop==True):
        data = data.drop(var,axis=1)
    return(data)

In [9]:
#X_train = one_hot_encoding(X_train,'order_HourGroup')

X_dev = one_hot_encoding(X_dev,'order_HourGroup')
#X_dev = one_hot_encoding(X_dev,'season')
#X_dev = one_hot_encoding(X_dev,'night')


#X_test = one_hot_encoding(X_test,'order_HourGroup')
#X_test = one_hot_encoding(X_test,'season')
#X_test = one_hot_encoding(X_test,'night')

#y_train=one_hot_encoding(y_train,'order_HourGroup')


In [10]:
X_dev.head()

Unnamed: 0  reordered  product_popularity_cnt  department_popularity_cnt  \
0     1612274          1                0.024617                   0.929434   
1      404649          1                0.020455                   0.929434   
2     2553704          1                0.115153                   0.929434   
3     2288426          1                0.115153                   0.929434   
4     3099956          1                0.064592                   0.929434   

   IsOrganic  days_previous_Group  Percentage_amount_product  \
0          1                    1                     0.0625   
1          1                    1                     0.1875   
2          0                    2                     0.2500   
3          0                    4                     0.0625   
4          1                    4                     0.0625   

   order_HourGroup_18-24  order_HourGroup_06-12  order_HourGroup_00-06  \
0                      1                      0                      0   
1                      0                      1                      0   
2                      0                      0                      1   
3                      0                      0                      0   
4                      1                      0                      0   

   order_HourGroup_12-18  
0                      0  
1                      0  
2                      0  
3                      1  
4                      0

##  Which models could be ran for multilable outcomes?
 
Following the recommendations of sklearn (https://scikit-learn.org/stable/modules/multiclass.html) the following models accept multilabel outcomes:
 
Support multilabel:
- sklearn.linear_model.RidgeClassifierCV
- sklearn.tree.DecisionTreeClassifier
- sklearn.tree.ExtraTreeClassifier
- sklearn.ensemble.ExtraTreesClassifier
- sklearn.ensemble.RandomForestClassifier
- sklearn.neighbors.KNeighborsClassifier
- sklearn.neighbors.RadiusNeighborsClassifier
 
Also, there is a technique called label powerset (in skmultilearn) that is able to take possible correlations between class labels into account.

In [18]:
#import sys
#!{sys.executable} -m pip install scikit-multilearn

    100% |████████████████████████████████| 92kB 673kB/s ta 0:00:011
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [11]:
# using Label Powerset
from skmultilearn.problem_transform import LabelPowerset
from sklearn.linear_model import LogisticRegression


## THIS IS THE PART THAT YOU MISS... THE MULTILEVEL-Y HAS TO BE TRANSFORMED INTO A NUMPY ARRAY (WITHOUT THE PRODUCT CODE)...

In [12]:
y_dev.head()
ydev = y_dev.copy()
ydev = np.array(ydev)
ydev = np.delete(ydev, 0, 1) 
print(ydev.shape)
print(ydev)

(402512, 30)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [36]:
type(ydev)

numpy.ndarray

# Also, the first column of the X must be deleted for the model (you don't want to enter an id to the model!)

In [116]:
X_dev.head()

Unnamed: 0  reordered  product_popularity_cnt  department_popularity_cnt  \
0     1612274          1                0.024617                   0.929434   
1      404649          1                0.020455                   0.929434   
2     2553704          1                0.115153                   0.929434   
3     2288426          1                0.115153                   0.929434   
4     3099956          1                0.064592                   0.929434   

   IsOrganic  days_previous_Group  Percentage_amount_product  \
0          1                    1                     0.0625   
1          1                    1                     0.1875   
2          0                    2                     0.2500   
3          0                    4                     0.0625   
4          1                    4                     0.0625   

   order_HourGroup_18-24  order_HourGroup_06-12  order_HourGroup_00-06  \
0                      1                      0                      0   
1                      0                      1                      0   
2                      0                      0                      1   
3                      0                      0                      0   
4                      1                      0                      0   

   order_HourGroup_12-18  
0                      0  
1                      0  
2                      0  
3                      1  
4                      0

In [94]:

Xdev = X_dev.copy()
Xdev = Xdev.drop(['Unnamed: 0'],axis=1)
print(Xdev.shape)
Xdev.head()

(402512, 10)


reordered  product_popularity_cnt  department_popularity_cnt  IsOrganic  \
0          1                0.024617                   0.929434          1   
1          1                0.020455                   0.929434          1   
2          1                0.115153                   0.929434          0   
3          1                0.115153                   0.929434          0   
4          1                0.064592                   0.929434          1   

   days_previous_Group  Percentage_amount_product  order_HourGroup_18-24  \
0                    1                     0.0625                      1   
1                    1                     0.1875                      0   
2                    2                     0.2500                      0   
3                    4                     0.0625                      0   
4                    4                     0.0625                      1   

   order_HourGroup_06-12  order_HourGroup_00-06  order_HourGroup_12-18  
0                      0                      0                      0  
1                      1                      0                      0  
2                      0                      1                      0  
3                      0                      0                      1  
4                      0                      0                      0

# NOTE: ALL THE MODELS MUST BE ENVELOPED INTO THE FUNCTION 
 
# "LabelPowerset()" . 
 
### This function convert the model to a multi-label format. Without it, some models will fail to understand that you are working with a multilabel outcome!

In [95]:
# initialize label powerset multi-label classifier
classifier = LabelPowerset(LogisticRegression())


In [96]:
# train
classifier.fit(Xdev, ydev)


/home/karpati/anaconda3/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/karpati/anaconda3/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LabelPowerset(classifier=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       require_dense=[True, True])

In [97]:
# predict
predictions = classifier.predict(Xdev)

In [18]:
#predictions

In [98]:
predictions.shape

(402512, 30)

# NOTE: The output prediction is in a special format called "lil_matrix" (list of lists format). 
 
### This is a sparce matrix that enables the model to work faster. However, the format is not recognized by many of the model operators. We need to convert them back to an numpy array...

In [99]:
type(predictions)

scipy.sparse.lil.lil_matrix

In [101]:
predictions2 = np.array(predictions.todense())
predictions2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# By summing the columns of the multilabel outcome and prediction we can get a sense of what is going on and how the model is behaving....

In [117]:
print(np.sum(ydev,axis=0))
print(ydev.shape)

[ 7060  8275  8554  8271 37375 14213  7396 25961  7069 23754 11316 46049
 10615 13719 13604 13616  8756  8048  7210  9863  8248  7710  7395 10502
  7906 20866 15349 16773  7616  9423]
(402512, 30)


In [118]:

print(np.sum(predictions2,axis=0))
print(predictions2.shape)

[    5    77     0     0 39975 36854   230 53788     0 27525  1480 46049
 11011 10729 17396 43419  8871   314     0 19489  1903   407  7395  1634
     0 19128 27996 22729  3824   284]
(402512, 30)


# And we calculate the accuracy using the score() function and/or the hamming score (see at the begining of the notebook).

In [105]:
classifier.score(Xdev,ydev)

#import ml_metrics as metrics

#metrics.auc(ydev,predictions.todense())
#accur(ydev,predictions2)

0.39048773701156736

In [106]:
hamming_score(ydev, predictions2)

0.39048773701156736

In [119]:
## If we have a perfect match then we will get one!
hamming_score(ydev, ydev)

1.0

# Ridge - Logistic Regression with L2 regularization

In [61]:
from sklearn.linear_model import RidgeClassifier, RidgeClassifierCV
# Initialize the predictive model object
#mod_logistic = LogisticRegression()


# Please see that we envelope the model with the LabelPowerset() function!

In [107]:
# Train the model using the training sets
#mod_logistic.fit(X_train, y_train)
mod = LabelPowerset(RidgeClassifierCV())
mod.fit(Xdev, ydev)

LabelPowerset(classifier=RidgeClassifierCV(alphas=array([ 0.1,  1. , 10. ]), class_weight=None,
         cv=None, fit_intercept=True, normalize=False, scoring=None,
         store_cv_values=False),
       require_dense=[True, True])

In [108]:
# Make predictions using the testing set
pred = mod.predict(Xdev)

In [109]:
print(type(pred))
print(pred.shape)

<class 'scipy.sparse.lil.lil_matrix'>
(402512, 30)


In [110]:
pred2 = np.array(pred.todense())

In [111]:
#print(np.sum(pred2,axis=1))
print(np.sum(pred2,axis=0))
print(pred2.shape)

[     0      0      0      0 133373  11609      0  26672      0  34269
      0  89350      0      0  28615    437      0      0      0    432
      0      0      0      0      0  49718  21055   6982      0      0]
(402512, 30)


In [113]:
mod.score(Xdev,ydev)

0.24100647930993363